.TH AX25IPD 1 "2 February 1997" Linux "Linux Programmer's Manual"
.SH NAME
ax25ipd \- AX.25 into IP Encapsulator
.SH SYNOPSIS
.B ax25ipd [config-file]
.SH DESCRIPTION
.LP
.B ax25ipd
is an RFC1226 compliant daemon capable of providing the encapsualtion
neccessary to send and receive AX.25 traffic across an IP transport.
.LP
Normally invoked as part of the boot order network initialisation,
.B ax25ipd
is capable of talking directly to a serial port connected tnc, or over
a pipe to a linux AX.25 port. KAM DE Dual Port Kiss is also supported 
in this release.
.LP
.B ax25ipd
can be run as a pure encapsulator, or as a digital repeater with a
functional callsign. Destination IP addresses are determined from a
hardcoded map of callsign/IP Address pairs.
.LP
.B ax25ipd
defaults to using
.B /etc/ax25/ax25ipd.conf
as it's config file ...
.LP
.SH OPTIONS
.TP 10
.BI \-v
Display the version. (yet to be implemented ...)
.SH FILES
/etc/ax25/ax25ipd.conf
.SH "SEE ALSO"
.BR ax25ipd.conf
.BR beacon (1),
.BR ax25 (4),
.BR netrom (4),
.BR rose (4),
.BR kissattach (8).
.LP
.SH BUGS
Routing needs to be looked at seriously, the method of routing is a real
hack, and improvements to it have only added to the hack.
.LP
Logging needs to be properly implemented.
.LP
Command line parsing needs to be properly implemented.
.LP
.B ax25ipd
should be part of the Linux AX.25 kernel support probably :-)
.SH AUTHORS
.nf
Michael Westerhof <Mike.Westerhof@Central.Sun.COM> <invalid address>
.br
Michael Durrant <>
.br
D. Jeff Dionne VE3DJF <Jeff@lnx_rpi.ee.ryerson.ca>
.br
Rob Mayfield VK5XXX/VK5ZEU <mayfieldrob@mail.dec.com>
.br
Terry Dawson VK2KTJ <terry@perf.no.itg.telstra.com.au>
.br
.fi
